server:
  port: 1112
# reids???????
spring:
  redis:
    host: 39.102.61.252
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        #???????????????8????????????????
        max-active: 8
        #??????????????????
        max-wait: -1
        #?????????????????????????8
        max-idle: 8
        #?????????ะก????????????????0
        min-idle: 0

